Makeup input
jkitz3/admin-panel-makeup pull request #3
Opened 2022-01-27 16:01 UTC by jkitz3

Файлы для инпутов в корне для того чтобы показать на gitpages.

2022-01-27 16:03 UTC, jkitz3 commented
На gitpages не отображается правильно видимо из-за названия файла ui-kit.html. С index.html в корне работало.

2022-01-29 17:57 UTC, Muslik requested changes
Прикреплю видео

2022-01-29 23:45 UTC, jkitz3 commented
Я не понял куда лучше привязывать иконки. По поведению не важно к обертке или к элементу. При ресайзинге обертки  иконка остается на месте.

2022-02-01 20:17 UTC, Muslik requested changes
Нужны доработки

2022-02-01 20:17 UTC, Muslik commented on blocks/ui-kit.html
> +              class="order-date__input button-color-default x-button"
Инпут и кнопка должны быть в одном контейнере. И позиционироваться кнопка должны относительно этого контейнера

2022-02-01 20:17 UTC, Muslik commented on index.html
> +            <label for="blankValue"
Не нужно вкладывать p внутрь label. Он тут вообще лишний

2022-02-01 20:17 UTC, Muslik commented on index.html
> +              value="06.12.2021"
pointer events это конечно круто ) Но нужно сделать чтобы это работало если я инпуту задам аттрибут disabled. (В вашем случае цвет не по макету становится).
Обычно это как работает. Например в React (который вы дальше будете учить) у инпута высталяется disabled если необходимо. И добавляется класс disabled соответственно. Поэтому в случае

2022-02-01 20:17 UTC, Muslik commented on index.html
> +              placeholder="Введите"
Цвет placeholder-а не по макету

2022-02-10 15:14 UTC, jkitz3 commented on blocks/ui-kit.html
> +              class="order-date__input button-color-default x-button"
Переделал

2022-02-10 15:14 UTC, jkitz3 commented on index.html
> +            <label for="blankValue"
Убрал p тег.

2022-02-10 15:15 UTC, jkitz3 commented on index.html
> +              value="06.12.2021"
Посмотрел еще раз про БЭМ и переделал html.

2022-02-10 15:15 UTC, jkitz3 commented on index.html
> +              placeholder="Введите"
Исправил.

2022-02-16 17:59 UTC, jkitz3 commented
Ссылка на страницу: https://jkitz3.github.io/admin-panel-makeup/blocks/ui-kit.html

2022-02-17 21:37 UTC, Muslik approved these changes

2022-02-18 02:59 UTC, merged