Makeup search bar
jkitz3/admin-panel-makeup pull request #4
Opened 2022-01-30 10:23 UTC by jkitz3

2022-01-30 19:14 UTC, jkitz3 commented
Ссылка https://jkitz3.github.io/admin-panel-makeup/

2022-02-01 20:35 UTC, Muslik requested changes
Нужны доработки

2022-02-01 20:35 UTC, Muslik commented on blocks/search-bar.css
> +.ui-kit__searchbar {
Цвет placeholder не по макету

2022-02-01 20:35 UTC, Muslik commented on blocks/search-bar.css
> +.searchbar__input-icon_blank {
А для чего абсолютно одинаковые стили ? Просто же .input можно сделать. Модификаторы бесполезны тут

2022-02-01 20:35 UTC, Muslik commented on blocks/ui-kit.html
> +            <button
Инпут и кнопка должны быть в одном контейнере. И позиционироваться кнопка должны относительно этого контейнера

2022-02-01 20:35 UTC, Muslik commented on blocks/ui-kit.html
> +            <button
Это же относится и к иконке

2022-02-01 20:35 UTC, Muslik commented on blocks/search-bar.css
> +  flex-direction: column;
Блоки и так будут друго под другом нет необходимости во flex-е

2022-02-16 17:55 UTC, jkitz3 commented on blocks/search-bar.css
> +.ui-kit__searchbar {
Поправил.

2022-02-16 17:56 UTC, jkitz3 commented on blocks/search-bar.css
> +.searchbar__input-icon_blank {
Переделал.

2022-02-16 17:56 UTC, jkitz3 commented on blocks/ui-kit.html
> +            <button
Переделал.

2022-02-16 17:56 UTC, jkitz3 commented on blocks/search-bar.css
> +.ui-kit__searchbar {
Поправил.

2022-02-16 17:57 UTC, jkitz3 commented on blocks/search-bar.css
> +  flex-direction: column;
Убрал лишнее.

2022-02-17 21:34 UTC, Muslik approved these changes

2022-02-17 21:36 UTC, Muslik requested changes
Не вижу результата в github pages

2022-02-18 03:51 UTC, jkitz3 commented
Ссылка https://jkitz3.github.io/admin-panel-makeup/

2022-02-20 05:36 UTC, Muslik approved these changes
Исправьте замечание

2022-02-20 05:36 UTC, Muslik commented on index.html
> +                class="button searchbar__button searchbar__button_x-button"
searchbar__button_x-button лишний класс. Перенесите его стили в searchbar__button

2022-02-25 19:17 UTC, merged