Added checkbox and radio
jkitz3/admin-panel-makeup pull request #5
Opened 2022-02-26 06:44 UTC by jkitz3

2022-02-26 13:00 UTC, jkitz3 commented
Страница https://github.com/jkitz3/admin-panel-makeup/settings/pages

2022-03-04 07:55 UTC, Muslik requested changes

2022-03-04 07:55 UTC, Muslik commented on blocks/ui-kit.html
> +            <div class="checkbox__content">
У checked checkbox-a и radio есть border. На макете их нет

2022-03-04 07:55 UTC, Muslik commented on blocks/ui-kit.html
> +            <div class="checkbox__content">
Я хочу чтобы я ваш чекбокс мог выдернуть и вставить в любое место на странице. С вашим я это сделать не могу. Нет какого то родителя, внутри сразу два чекбокса. Должен быть просто готовый блок 16x16 без каких то отступов. Отступы задает родитель через элемент (например: wrapper__section - wrapper - родитель, section - элемент). Можете поспрашивать у коллег еще

2022-03-06 05:18 UTC, jkitz3 commented on blocks/ui-kit.html
> +            <div class="checkbox__content">
> У checked checkbox-a и radio есть border. На макете их нет

У checkbox-а есть border или я не что-то не так понял?
.checkbox__container::before {
  content: "";
  display: inline-block;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
  height: 16px;
  width: 16px;
  border: 1px solid #bad8f5;
  border-radius: 2px;
  background-color: #fff;
}
.checkbox__container::after {
  content: "";
  display: inline-block;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 2;
  height: 16px;
  width: 16px;
  border: 1px solid #bad8f5;
  border-radius: 2px;
  background-image: url(./icons/checkmark.svg);
  background-repeat: no-repeat;
  opacity: 0;
}

2022-03-06 07:04 UTC, jkitz3 commented on blocks/ui-kit.html
> +            <div class="checkbox__content">
> Я хочу чтобы я ваш чекбокс мог выдернуть и вставить в любое место на странице. С вашим я это сделать не могу. Нет какого то родителя, внутри сразу два чекбокса. Должен быть просто готовый блок 16x16 без каких то отступов. Отступы задает родитель через элемент (например: wrapper__section - wrapper - родитель, section - элемент). Можете поспрашивать у коллег еще

Переделал. Теперь достаточно взять классы checkbox или radio с детьми, чтобы поместить их в любое место.

2022-03-08 20:02 UTC, Muslik requested changes
Есть замечания

2022-03-08 20:02 UTC, Muslik commented on blocks/checkbox-radio.css
> +  flex-direction: row !important;
от important избавиться

2022-03-08 20:02 UTC, Muslik commented on blocks/checkbox-radio.css
> +}
https://ibb.co/NsTYpTf
У чекнутого блока нет бордера

2022-03-08 20:02 UTC, Muslik commented on blocks/checkbox-radio.css
> +.radio__input:checked + .radio__container::after {
https://ibb.co/17HdYGP
У вас если убрать отступы от блока, checkbox все равно не 16x16

2022-03-08 20:02 UTC, Muslik commented on blocks/search-bar.css
> +  padding-left: 32px !important;
от important избавиться

2022-03-08 20:02 UTC, Muslik commented on blocks/style.css
> +.ui-kit__block_checkbox-radio {
checkbox_radio не может быть модификатором

2022-03-08 20:02 UTC, Muslik commented on blocks/style.css
> +  flex-direction: row;
Это дефолтное поведение у flex

2022-03-08 20:02 UTC, Muslik commented on blocks/style.css
> +  min-width: 104px;
Это конечно к верстке не относится, но можно не указывать такие жесткие размеры у блоков. Сделать блок inline-block или flex и добавьте padding нужный и размер сам станет красивым

2022-03-20 18:13 UTC, jkitz3 commented on blocks/search-bar.css
> +  padding-left: 32px !important;
Убрал

2022-03-20 18:13 UTC, jkitz3 commented on blocks/checkbox-radio.css
> +  flex-direction: row !important;
Убрал

2022-03-20 18:57 UTC, jkitz3 commented on blocks/style.css
> +  flex-direction: row;
Убрал

2022-03-20 19:15 UTC, jkitz3 commented on blocks/style.css
> +  min-width: 104px;
Убрал жесткие размеры

2022-03-20 19:23 UTC, jkitz3 commented on blocks/checkbox-radio.css
> +}
Убрал

2022-03-20 19:27 UTC, jkitz3 commented on blocks/checkbox-radio.css
> +.radio__input:checked + .radio__container::after {
Убрал бордер у чекнутого checkbocx и radio. У меня в браузере отображается размер 16х16. Картинка уже удалена - посмотреть не могу.

2022-03-20 19:35 UTC, jkitz3 commented on blocks/style.css
> +.ui-kit__block_checkbox-radio {
Мне непонятно почему ui-kit__block_checkbox-radio не может быть модификатором для ui-kit__block. Как тогда лучше поступить, если мне только для этого блока нужно поменять паддинг с 48px на 24px?

2022-03-21 20:14 UTC, jkitz3 commented
Ссылка: https://jkitz3.github.io/admin-panel-makeup/blocks/ui-kit.html

2022-03-22 19:45 UTC, Muslik commented on blocks/style.css
> +.ui-kit__block_checkbox-radio {
Модификатор не может называться checkbox-radio.

[Название модификатора](https://ru.bem.info/methodology/naming-convention/#%D0%98%D0%BC%D1%8F-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%B0-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0) характеризует внешний вид («какой размер?», «какая тема?» и т. п. — «размер»: size_s, «тема»: theme_islands), состояние («чем отличается от прочих?» — «отключен»: disabled, «фокусированный»: focused) и поведение («как ведет себя?», «как взаимодействует с пользователем?» — «направление»: directions_left-top).

2022-03-22 22:58 UTC, Muslik requested changes
https://ibb.co/k845vs3

По поводу модификатора ответил. Размер чекбокса должен быть 16x16

2022-03-23 18:05 UTC, jkitz3 commented on blocks/style.css
> +.ui-kit__block_checkbox-radio {
Переименовал

2022-03-23 18:18 UTC, jkitz3 commented
> https://ibb.co/k845vs3
> 
> По поводу модификатора ответил. Размер чекбокса должен быть 16x16

Поправил название модификатора, чекбоксы и радио теперь 16х16.
Ссылка: https://jkitz3.github.io/admin-panel-makeup/blocks/ui-kit.html

2022-03-24 08:47 UTC, Muslik requested changes
https://ibb.co/w7VpzKs - если я убираю margin у элемента block__checkbox, block__radio, все равно есть отступ. Значит он не 16x16 :)

2022-03-25 02:49 UTC, jkitz3 commented
> https://ibb.co/w7VpzKs - если я убираю margin у элемента block__checkbox, block__radio, все равно есть отступ. Значит он не 16x16 :)

Поправил

2022-03-27 22:46 UTC, Muslik approved these changes

2022-04-03 13:35 UTC, jkitz3 commented
Исправлено в других ветках.

2022-04-03 13:35 UTC, closed without merging