Makeup button
jkitz3/admin-panel-makeup pull request #6
Opened 2022-02-26 12:53 UTC by jkitz3

Использовал !Important, так как не получалось при импорте стилей элементов кита в общий файл стилей отобразить правильно по-другому.

2022-02-26 13:09 UTC, jkitz3 commented
Ссылка https://jkitz3.github.io/admin-panel-makeup/

2022-03-04 07:58 UTC, Muslik requested changes
Избавиться от important, убрать лишние обертки у иконок

2022-03-04 07:58 UTC, Muslik commented on blocks/button.css
> +  flex-direction: row !important;
important быть не должно.

2022-03-04 07:58 UTC, Muslik commented on blocks/ui-kit.html
> +                  <div class="button-block__icon">
Не нужна лишняя обертка. У вас есть текст и есть класс иконки. Завяжитесь на них. Если есть иконка и рядом текст то у текста делаете отступ

2022-03-04 08:00 UTC, Muslik commented
> Использовал !Important, так как не получалось при импорте стилей элементов кита в общий файл стилей отобразить правильно по-другому.

important это лишнее повышение специфичности и такого быть не должно. Посоветуйтесь со своими одногруппниками

2022-03-04 08:01 UTC, Muslik commented
У вас в чисто голубой кнопке завязка на то что дефолтный цвет иконки белый. (.icon { fill: #fff }). Лучше все таки завязаться на тему и цвет иконки указать в зависимости от нее

2022-03-06 08:16 UTC, jkitz3 commented on blocks/button.css
> +  flex-direction: row !important;
Переделал без important.

2022-03-06 09:05 UTC, jkitz3 commented on blocks/ui-kit.html
> +                  <div class="button-block__icon">
Убрал лишнюю обертку для иконки.

2022-03-06 09:11 UTC, jkitz3 commented
> У вас в чисто голубой кнопке завязка на то что дефолтный цвет иконки белый. (.icon { fill: #fff }). Лучше все таки завязаться на тему и цвет иконки указать в зависимости от нее

Убрал из иконки дефолтный белый цвет.

2022-03-08 20:06 UTC, Muslik approved these changes
Малюсенькое замечание к модификатору

2022-03-08 20:06 UTC, Muslik commented on blocks/button.css
> +.button_size_default + .button_icon_only {
_icon_only думаю должен быть _icon-only.

2022-03-20 18:05 UTC, jkitz3 commented on blocks/button.css
> +.button_size_default + .button_icon_only {
Поправил

2022-04-03 13:34 UTC, closed without merging

2022-04-03 13:35 UTC, jkitz3 commented
Исправлено в других ветках.