Makeup dropdown
jkitz3/admin-panel-makeup pull request #7
Opened 2022-02-27 20:20 UTC by jkitz3

Makeup dropdown

2022-02-27 20:22 UTC, jkitz3 commented
Ссылка https://jkitz3.github.io/admin-panel-makeup/

2022-03-04 08:05 UTC, Muslik requested changes

2022-03-04 08:05 UTC, Muslik commented on blocks/ui-kit.html
> +                          >Отложен</label
Иконок radio кнопок быть не должно

2022-03-04 08:05 UTC, Muslik commented on blocks/ui-kit.html
> +                    <div class="checkbox checkbox-dropdown__checkbox">
В figma этот блок тянется на всю ширину. У вас между строками есть отступ: https://ibb.co/wJC4bxL. Соответственно я могу кликнуть в пустое место между блоками и ничего не произойдет. Используйте padding. Тоже касается и radio

2022-03-04 08:05 UTC, Muslik commented on blocks/ui-kit.html
> +                    class="button select-theme__button button_theme_link button_size_small"
Вытягивание на всю ширину сделайте модификатором для блока button. ( вы ведь можете расширять ее)
.button_full-width например.

2022-03-06 10:24 UTC, jkitz3 commented on blocks/ui-kit.html
> +                          >Отложен</label
Убрал radio__container_dropdown

2022-03-06 11:45 UTC, jkitz3 commented on blocks/ui-kit.html
> +                    class="button select-theme__button button_theme_link button_size_small"
Добавил модификатор button_full-width

2022-03-06 13:31 UTC, jkitz3 commented on blocks/ui-kit.html
> +                    <div class="checkbox checkbox-dropdown__checkbox">
Сделал, но не через padding.

2022-03-08 20:21 UTC, Muslik requested changes
https://codepen.io/Dzhab/pen/BameMYx?editors=1100 - вот чего я от вас жду. У каждого блока - отдельное место для нажатия что достигается именно padding-ом.

У radio dropdown-а не должно быть круглешков. Посмотрите на макет!

2022-03-21 17:52 UTC, jkitz3 commented
> https://codepen.io/Dzhab/pen/BameMYx?editors=1100 - вот чего я от вас жду. У каждого блока - отдельное место для нажатия что достигается именно padding-ом.
> 
> У radio dropdown-а не должно быть круглешков. Посмотрите на макет!

Сергей на каком-то занятии сказал, что это ошибка в макете и круглешки там быть должны.

2022-03-21 20:04 UTC, jkitz3 commented
Ссылка: https://jkitz3.github.io/admin-panel-makeup/blocks/ui-kit.html

2022-03-22 19:43 UTC, Muslik approved these changes
Смотрим еще раз пример https://codepen.io/Dzhab/pen/BameMYx?editors=1100
Блоки одинакового размера центрированы внутри блока. 
https://ibb.co/9qL4V6Q - в вашем случае такого нет.
Я сейчас это приму, но в компоненте реакта будет хорошо если вы это исправите.

Касательно круглешков уточнял у дизайнера. Их быть не должно.

2022-03-22 19:48 UTC, Muslik requested changes
checkbox должен быть 16x16. https://ibb.co/6wTDPqq
Тоже самое касаеся radio.
На счет модификатора написал

2022-03-23 19:23 UTC, jkitz3 commented
> Смотрим еще раз пример https://codepen.io/Dzhab/pen/BameMYx?editors=1100 Блоки одинакового размера центрированы внутри блока. https://ibb.co/9qL4V6Q - в вашем случае такого нет. Я сейчас это приму, но в компоненте реакта будет хорошо если вы это исправите.
> 
> Касательно круглешков уточнял у дизайнера. Их быть не должно.

В компонентах постараюсь отцентрировать - пока получается криво. Кругляшки убрал.

2022-03-23 19:24 UTC, jkitz3 commented
> checkbox должен быть 16x16. https://ibb.co/6wTDPqq Тоже самое касаеся radio. На счет модификатора написал

Поправил

2022-03-24 08:48 UTC, Muslik requested changes
Замечание от чекбокса подтянуть сюда

2022-03-25 02:49 UTC, jkitz3 commented
> Замечание от чекбокса подтянуть сюда

Поправил

2022-03-27 22:46 UTC, Muslik approved these changes

2022-04-03 13:12 UTC, merged