List mock
jkitz3/admin-panel-makeup pull request #8
Opened 2022-02-28 19:07 UTC by jkitz3

List mock

2022-03-04 08:08 UTC, Muslik requested changes

2022-03-04 08:08 UTC, Muslik commented on mocks/list.js
> +    "order-status": "Отменен",
Так. В JS принято использовать camelCase, поэтому orderStatus и без кавычек

2022-03-04 08:08 UTC, Muslik commented on mocks/utils.js
> +  return Array.isArray(array)
Это все конечно хорошо, но вы делаете функцию которой сами будете пользоваться :) И вы себе не доверяете? И мало того что это функция не отфильтрует, она мне просто вернет строку. Тогда уж нужно выбрасывать ошибку если вы передали не массив

2022-03-06 10:57 UTC, jkitz3 commented on mocks/list.js
> +    "order-status": "Отменен",
Поправил

2022-03-06 11:08 UTC, jkitz3 commented on mocks/utils.js
> +  return Array.isArray(array)
Убрал проверку

2022-03-06 18:33 UTC, Muslik approved these changes
Мелкое замечание

2022-03-06 18:33 UTC, Muslik commented on mocks/utils.js
> +  return array.filter((item) => item["orderStatus"] === status);
item["orderStatus"] -> item.orderStatus

2022-03-06 19:33 UTC, jkitz3 commented on mocks/utils.js
> +  return array.filter((item) => item["orderStatus"] === status);
Поправил

2022-03-08 20:21 UTC, Muslik approved these changes

2022-04-03 13:18 UTC, merged